services:
  spark-master:
    build: .
    image: perception-tree-rings:latest
    container_name: spark-master
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/spark*.out"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/spark/data
    env_file:
      - ./.env

  spark-worker:
    build: .
    image: perception-tree-rings:latest
    depends_on:
      - spark-master
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/spark*.out"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./data:/opt/spark/data
    env_file:
      - ./.env